services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "80:80"
    container_name: nginx
    restart: unless-stopped
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped