services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    container_name: nginx
    env_file: ../.env
    depends_on:
      - wordpress
    restart: always
    volumes:
      - /home/csilva-m/data/wordpress:/var/www/html
    networks:
      inception:
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: ../.env
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      inception:
    healthcheck:
      test: ["CMD", "wp", "core", "is-installed", "--allow-root"]
      interval: 15s
      timeout: 10s
      retries: 5
  
  mariadb:
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: ../.env
    restart: always
    build: ./requirements/mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      inception:

networks:
  inception:

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/csilva-m/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/csilva-m/data/mariadb

