services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    container_name: nginx
    # env_file: .env
    depends_on:
      - wordpress
    restart: always
    volumes:
      - /home/csilva-m/data/wordpress:/var/www/html
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    # env_file: .env
    depends_on:
      - mariadb
    restart: always
    volumes:
      - /home/csilva-m/data/wordpress:/var/www/html
  
  mariadb:
    container_name: mariadb
    # env_file: .env
    restart: always
    build: ./requirements/mariadb
